# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

#Allow repo secrets
env:
  VITE_INSTAGRAM_SECRET: ${{ secrets.VITE_INSTAGRAM_SECRET }}
  VITE_FACEBOOK_SECRET: ${{ secrets.VITE_FACEBOOK_SECRET }}
  VITE_TIKTOK_SECRET: ${{ secrets.VITE_TIKTOK_SECRET }}
  VITE_TELEGRAM_SECRET: ${{ secrets.VITE_TELEGRAM_SECRET }}
  VITE_EMAIL_SECRET: ${{ secrets.VITE_EMAIL_SECRET }}

  VITE_TITLE_SECRET: ${{ secrets.VITE_TITLE_SECRET }}
  VITE_TITLE_SECRET_US: ${{ vars.VITE_TITLE_SECRET_US }}

  VITE_PROFILE_NAME_SECRET: ${{ secrets.VITE_PROFILE_NAME_SECRET }}
  VITE_PROFILE_DESCRIPTION_VARIABLE: ${{ vars.VITE_PROFILE_DESCRIPTION_VARIABLE }}
  VITE_PROFILE_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_PROFILE_DESCRIPTION_VARIABLE_US }}

  VITE_BUY_A_IMAGE_SECRET: ${{ secrets.VITE_BUY_A_IMAGE_SECRET }}
  VITE_BUY_A_IMAGE_DESCRIPTION_VARIABLE: ${{ vars.VITE_BUY_A_IMAGE_DESCRIPTION_VARIABLE }}
  VITE_BUY_A_IMAGE_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_BUY_A_IMAGE_DESCRIPTION_VARIABLE_US }}

  VITE_BUY_A_AUDIO_SECRET: ${{ secrets.VITE_BUY_A_AUDIO_SECRET }}
  VITE_BUY_A_AUDIO_DESCRIPTION_VARIABLE: ${{ vars.VITE_BUY_A_AUDIO_DESCRIPTION_VARIABLE }}
  VITE_BUY_A_AUDIO_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_BUY_A_AUDIO_DESCRIPTION_VARIABLE_US }}

  VITE_BUY_A_MUSIC_SECRET: ${{ secrets.VITE_BUY_A_MUSIC_SECRET }}
  VITE_BUY_A_MUSIC_DESCRIPTION_VARIABLE: ${{ vars.VITE_BUY_A_MUSIC_DESCRIPTION_VARIABLE }}
  VITE_BUY_A_MUSIC_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_BUY_A_MUSIC_DESCRIPTION_VARIABLE_US }}

  VITE_BUY_A_VIDEO_CLIP_SECRET: ${{ secrets.VITE_BUY_A_VIDEO_CLIP_SECRET }}
  VITE_BUY_A_VIDEO_CLIP_DESCRIPTION_VARIABLE: ${{ vars.VITE_BUY_A_VIDEO_CLIP_DESCRIPTION_VARIABLE }}
  VITE_BUY_A_VIDEO_CLIP_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_BUY_A_VIDEO_CLIP_DESCRIPTION_VARIABLE_US }}

  VITE_BUY_A_COURSE1_SECRET: ${{ secrets.VITE_BUY_A_COURSE1_SECRET }}
  VITE_BUY_A_COURSE1_DESCRIPTION_VARIABLE: ${{ vars.VITE_BUY_A_COURSE1_DESCRIPTION_VARIABLE }}
  VITE_BUY_A_COURSE1_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_BUY_A_COURSE1_DESCRIPTION_VARIABLE_US }}

  VITE_BUY_A_COURSE2_SECRET: ${{ secrets.VITE_BUY_A_COURSE2_SECRET }}
  VITE_BUY_A_COURSE2_DESCRIPTION_VARIABLE: ${{ vars.VITE_BUY_A_COURSE2_DESCRIPTION_VARIABLE }}
  VITE_BUY_A_COURSE2_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_BUY_A_COURSE2_DESCRIPTION_VARIABLE_US }}

  VITE_AFFILIATE_IMAGE_SECRET: ${{ secrets.VITE_AFFILIATE_IMAGE_SECRET }}
  VITE_AFFILIATE_IMAGE_DESCRIPTION_VARIABLE: ${{ vars.VITE_AFFILIATE_IMAGE_DESCRIPTION_VARIABLE }}
  VITE_AFFILIATE_IMAGE_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_AFFILIATE_IMAGE_DESCRIPTION_VARIABLE_US }}

  VITE_AFFILIATE_AUDIO_SECRET: ${{ secrets.VITE_AFFILIATE_AUDIO_SECRET }}
  VITE_AFFILIATE_AUDIO_DESCRIPTION_VARIABLE: ${{ vars.VITE_AFFILIATE_AUDIO_DESCRIPTION_VARIABLE }}
  VITE_AFFILIATE_AUDIO_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_AFFILIATE_AUDIO_DESCRIPTION_VARIABLE_US }}

  VITE_SPONSORSHIP_CONTACT_SECRET: ${{ secrets.VITE_SPONSORSHIP_CONTACT_SECRET }}
  VITE_SPONSORSHIP_CONTACT_DESCRIPTION_VARIABLE: ${{ vars.VITE_SPONSORSHIP_CONTACT_DESCRIPTION_VARIABLE }}
  VITE_SPONSORSHIP_CONTACT_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_SPONSORSHIP_CONTACT_DESCRIPTION_VARIABLE_US }}


  VITE_NUMLINKS: ${{ vars.VITE_NUMLINKS }}

  VITE_LINK1_SECRET: ${{ secrets.VITE_LINK1_SECRET }}
  VITE_LINK1_DESCRIPTION_VARIABLE: ${{ vars.VITE_LINK1_DESCRIPTION_VARIABLE }}
  VITE_LINK1_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_LINK1_DESCRIPTION_VARIABLE_US }}

  VITE_LINK2_SECRET: ${{ secrets.VITE_LINK2_SECRET }}
  VITE_LINK2_DESCRIPTION_VARIABLE: ${{ vars.VITE_LINK2_DESCRIPTION_VARIABLE }}
  VITE_LINK2_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_LINK2_DESCRIPTION_VARIABLE_US }}

  VITE_LINK3_SECRET: ${{ secrets.VITE_LINK3_SECRET }}
  VITE_LINK3_DESCRIPTION_VARIABLE: ${{ vars.VITE_LINK3_DESCRIPTION_VARIABLE }}
  VITE_LINK3_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_LINK3_DESCRIPTION_VARIABLE_US }}

  VITE_LINK4_SECRET: ${{ secrets.VITE_LINK4_SECRET }}
  VITE_LINK4_DESCRIPTION_VARIABLE: ${{ vars.VITE_LINK4_DESCRIPTION_VARIABLE }}
  VITE_LINK4_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_LINK4_DESCRIPTION_VARIABLE_US }}

  VITE_LINK5_SECRET: ${{ secrets.VITE_LINK5_SECRET }}
  VITE_LINK5_DESCRIPTION_VARIABLE: ${{ vars.VITE_LINK5_DESCRIPTION_VARIABLE }}
  VITE_LINK5_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_LINK5_DESCRIPTION_VARIABLE_US }}

  VITE_LINK6_SECRET: ${{ secrets.VITE_LINK6_SECRET }}
  VITE_LINK6_DESCRIPTION_VARIABLE: ${{ vars.VITE_LINK6_DESCRIPTION_VARIABLE }}
  VITE_LINK6_DESCRIPTION_VARIABLE_US: ${{ vars.VITE_LINK6_DESCRIPTION_VARIABLE_US }}

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clean previous build
        run: rm -rf ./dist

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

